### ISSUE TITLE
native scrollbars

### ISSUE THREAD

**Issue by otmjka** [leoselig/jsFancyScroll#2]
display native scrollbar: os x, firefox(latest), chrome(latest), safari

![2014-12-15 19 25 27](https://cloud.githubusercontent.com/assets/5286446/5437232/6a33a3f0-8490-11e4-8af6-aa75c26cb03b.png)

**Comment by abdelhady** [comment]
[This](https://github.com/leoselig/jsFancyScroll/pull/7) pull request should fix it

**Comment by leoselig** [comment]
I'm sorry I didn't have the time to responds to issues and PRs. I do not plan to maintain this project any longer as the need shrinked in the shadow of `::webkit-scrollbar` and co.
