### ISSUE TITLE
DIV not allowed inside UL

### ISSUE THREAD

**Issue by nkCreation** [leoselig/jsFancyScroll#4]
Hi. Searching a scrollbar plugin I found yours - but - i've seen something that alert me :

![image](https://cloud.githubusercontent.com/assets/4450152/20961854/2625c542-bc67-11e6-9b84-ef30ae9bf8fd.png)

You can't add a &lt;div&gt; element inside a &lt;ul&gt; element. This is not allowed by W3C specs. (Btw, it works with a div, so you just have to update the readme)

An other thing : you should tell that your plugin need jquery to work. It's not clear to just have it in the description ;)

Thank you !

**Comment by nkCreation** [comment]
@leoselig no news about this issue ?

**Comment by leoselig** [comment]
I'm sorry I didn't have the time to responds to issues and PRs. I do not plan to maintain this project any longer as the need shrinked in the shadow of `::webkit-scrollbar` and co.
